---
title: "map_options"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{map_options}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, eval=TRUE}
library(mapselector)
library(tidyverse)
library(sf)
library(leaflet)
library(rcartocolor)

data("CERQ")

# leaflet can make attractive colour palattes. 
interp_pal <- leaflet::colorFactor(rcartocolor::carto_pal(12,"Prism"), domain = CERQ$NOM_PROV_N)

## as a demo, make me a map

leaflet(CERQ) %>%
  addTiles() %>% # Affichage du fond de carte
  addPolygons(color = "darkblue", # couleur des limites des polygones
              weight = 1,
              smoothFactor = 0.5,
              layerId = ~NOM_PROV_N,
              fillColor = ~interp_pal(NOM_PROV_N), # couleur du remplissage des polygones
              fillOpacity = 0.7,
              highlightOptions = highlightOptions(color = "white",
                                                  weight = 4,
                                                  # fillOpacity = 0.,
                                                  bringToFront = TRUE)
  )


```
